email:
  imap_host: imap.host.com
  smtp_host: smtp.host.com
  account: name@host.com
  psw: password
  destination: folder_name

responds:
  default_content: 您好！我们已收到您的邮件！祝好！
  default_expire_content: 您好！您已超过回复此邮件的有效期限！谢谢您的支持！祝好！
  default_subject: 【no-reply】这是来自报名邮箱的自动回复
  r000:
    from: 2018-03-27 00:00:00 # specific YYYY-mm-dd HH:MM:SS time or -1 (now)
    to: 2018-04-01 00:00:00 # specific time
    save: true
    handle: true # if set true, need to provide a corresponding config yaml file in config/
    content: 您好！我们已收到您的邮件！祝好！
    expire_content: 您好！您已超过回复此邮件的有效期限！谢谢您的支持！祝好！

schedule:
  interval_minutes: 5